// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1682751540);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1682751534);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1682751531);
user_pref("calendar.list.sortOrder", "c4c0325d-4c4b-4491-bf05-3e09664b26e9");
user_pref("calendar.registry.c4c0325d-4c4b-4491-bf05-3e09664b26e9.calendar-main-default", true);
user_pref("calendar.registry.c4c0325d-4c4b-4491-bf05-3e09664b26e9.calendar-main-in-composite", true);
user_pref("calendar.registry.c4c0325d-4c4b-4491-bf05-3e09664b26e9.disabled", true);
user_pref("calendar.registry.c4c0325d-4c4b-4491-bf05-3e09664b26e9.name", "Home");
user_pref("calendar.registry.c4c0325d-4c4b-4491-bf05-3e09664b26e9.type", "storage");
user_pref("calendar.registry.c4c0325d-4c4b-4491-bf05-3e09664b26e9.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1682751539006");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1682751518);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230407145224");
user_pref("extensions.lastAppVersion", "102.10.0");
user_pref("extensions.lastPlatformVersion", "102.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"c919a66e-38e2-465b-a663-e3a173e4ca00\",\"google@search.mozilla.org\":\"a8bb87d5-c1a0-49b0-8d6f-9b9e45d27b84\",\"ddg@search.mozilla.org\":\"415c7278-0843-461b-844b-2437a23bad19\",\"amazondotcom@search.mozilla.org\":\"f889dddf-4401-43c4-8409-445ed689a42b\",\"wikipedia@search.mozilla.org\":\"26f49e26-bd8f-42d2-b485-dea2a02c61b2\",\"bing@search.mozilla.org\":\"6796da3b-2634-4894-b49d-5f071ab7235e\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "8d5e31af-1299-4729-932b-e65ee39d087");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "03f42e46-2925-44fe-991c-1c3fc28c8dad");
user_pref("toolkit.telemetry.previousBuildID", "20230407145224");
